In [1]:
import pandas as pd
import numpy as np

# Sample DataFrame
df = pd.DataFrame({
    'id1': [1, 1, 1, 2, 2, 3],
    'id2': [101, 102, 103, 201, 202, 301],
    'feature1': [10, 20, 30, 5, np.nan, 15],
    'feature2': [100, 150, 200, 50, 60, np.nan]
})

In [2]:
def calculate_statistics(group):
    numeric_group = group.select_dtypes(include=[np.number])

    #통계 계산
    mean_vals = numeric_group.mean()
    std_vals = numeric_group.std()
    min_vals = numeric_group.min()
    max_vals = numeric_group.max()

    stats={
        'count_id2':group['id2'].count(),#그룹에 있는 레코드의 수량
        'mean':mean_vals,
        'std':std_vals,
        'std_to_mean':std_vals/mean_vals.replace(0,np.nan), #np.nan을 0으로 대체
        'max':max_vals,
        'min':min_vals,
        'range_to_min':(max_vals - min_vals)/min_vals.replace(0,np.nan),
        'missing_record_count':numeric_group.isnull().sum().sum() #해당 column에 데이터가 비어있는 것
    }
    return pd.DataFrame(stats)

In [3]:
grouped_stats = df.groupby('id1').apply(calculate_statistics).reset_index()
#불필요한 멀티 레벨 index를 제거하고 column 이름을 정제(clean up)
grouped_stats.columns.name=None
grouped_stats.rename(columns={'index':'id1'}, inplace=True)

grouped_stats

C:\Users\Administrator\AppData\Local\Temp\ipykernel_7936\3128631948.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_stats = df.groupby('id1').apply(calculate_statistics).reset_index()

,id1,level_1,count_id2,mean,std,std_to_mean,max,min,range_to_min,missing_record_count
0,1,id1,3,1.0,0.000000,0.000000,1.0,1.0,0.000000,0
1,1,id2,3,102.0,1.000000,0.009804,103.0,101.0,0.019802,0
2,1,feature1,3,20.0,10.000000,0.500000,30.0,10.0,2.000000,0
3,1,feature2,3,150.0,50.000000,0.333333,200.0,100.0,1.000000,0
4,2,id1,2,2.0,0.000000,0.000000,2.0,2.0,0.000000,1
5,2,id2,2,201.5,0.707107,0.003509,202.0,201.0,0.004975,1
6,2,feature1,2,5.0,NaN,NaN,5.0,5.0,0.000000,1
7,2,feature2,2,55.0,7.071068,0.128565,60.0,50.0,0.200000,1
8,3,id1,1,3.0,NaN,NaN,3.0,3.0,0.000000,1
9,3,id2,1,301.0,NaN,NaN,301.0,301.0,0.000000,1
10,3,feature1,1,15.0,NaN,NaN,15.0,15.0,0.000000,1
11,3,feature2,1,NaN,NaN,NaN,NaN,NaN,NaN,1

In [4]:
data = {
    'EmployeeID': ['F0099','F1010','M2020','M2021','E0100','E1000','E3434'],
    'Name': ['Alice', 'Bob', 'Charlie','John','Sean','Tobias','Francois'],     # Column 'Name' with names
    'Age': [25, 30, 35,50,47,59,55],                      # Column 'Age' with ages
    'Division': ['Finance','Finance','Marketing','Marketing','Engineering','Engineering','Engineering'],
    'City': ['New York', 'Los Angeles', 'Beijing','Hong Kong','London','Beijing','London'],  # Column 'City' with cities
    'Salary': [70000, 80000, 60000,45000,125000,36000,250000],# Column 'Salary' with salaries
    'Bonus': [1000,1500,30000,23000,20000,25000,15000]
}

# Step 3: Create the DataFrame
df = pd.DataFrame(data)
df.set_index('EmployeeID',inplace=True)

# Display the DataFrame
df

                Name  Age     Division         City  Salary  Bonus
EmployeeID
F0099          Alice   25      Finance     New York   70000   1000
F1010            Bob   30      Finance  Los Angeles   80000   1500
M2020        Charlie   35    Marketing      Beijing   60000  30000
M2021           John   50    Marketing    Hong Kong   45000  23000
E0100           Sean   47  Engineering       London  125000  20000
E1000         Tobias   59  Engineering      Beijing   36000  25000
E3434       Francois   55  Engineering       London  250000  15000

In [5]:
dfGroupedByDivision = df.groupby('Division')
for devision, group in dfGroupedByDivision:
    print('I have found:', devision)
    print(group)

I have found: Engineering
                Name  Age     Division     City  Salary  Bonus
EmployeeID
E0100           Sean   47  Engineering   London  125000  20000
E1000         Tobias   59  Engineering  Beijing   36000  25000
E3434       Francois   55  Engineering   London  250000  15000
I have found: Finance
             Name  Age Division         City  Salary  Bonus
EmployeeID
F0099       Alice   25  Finance     New York   70000   1000
F1010         Bob   30  Finance  Los Angeles   80000   1500
I have found: Marketing
               Name  Age   Division       City  Salary  Bonus
EmployeeID
M2020       Charlie   35  Marketing    Beijing   60000  30000
M2021          John   50  Marketing  Hong Kong   45000  23000

In [6]:
for division, group in dfGroupedByDivision:
    print('I have found : ', division)
    if division == 'Engineering':
        print('I am processing : ', division)
        print(group)
        topEarner = group['Salary'].max()
        print('The highest salary in the group is : ', topEarner)
        print("\n")

I have found :  Engineering
I am processing :  Engineering
                Name  Age     Division     City  Salary  Bonus
EmployeeID
E0100           Sean   47  Engineering   London  125000  20000
E1000         Tobias   59  Engineering  Beijing   36000  25000
E3434       Francois   55  Engineering   London  250000  15000
The highest salary in the group is :  250000


I have found :  Finance
I have found :  Marketing

In [7]:
def custom_calculation(group_data, group_name, multiplier):
    # 실제 연산
    result = group_data * multiplier
    return result

multiplier_map = {
    'Engineering': 10,
    'Finance': 5,
    'Marketing': 2
}

for division, group in df.groupby('Division'):
    target_number = multiplier_map[division]
    df.loc[group.index, 'total_salary'] = custom_calculation(group['Salary'], group['Bonus'], target_number)
df

,Name,Age,Division,City,Salary,Bonus,total_salary
EmployeeID,,,,,,,
F0099,Alice,25,Finance,New York,70000,1000,350000.0
F1010,Bob,30,Finance,Los Angeles,80000,1500,400000.0
M2020,Charlie,35,Marketing,Beijing,60000,30000,120000.0
M2021,John,50,Marketing,Hong Kong,45000,23000,90000.0
E0100,Sean,47,Engineering,London,125000,20000,1250000.0
E1000,Tobias,59,Engineering,Beijing,36000,25000,360000.0
E3434,Francois,55,Engineering,London,250000,15000,2500000.0

In [8]:
def my_diff(x) : 
    max_data = x.max()
    min_data = x.min()
    return "최대와 최소의 차이" + str(10*max_data - min_data)
df.groupby(['Division', 'City']).agg({'Salary':['sum',my_diff], 'Bonus':'mean',})

                         Salary                       Bonus
                            sum            my_diff     mean
Division    City
Engineering Beijing       36000   최대와 최소의 차이324000  25000.0
            London       375000  최대와 최소의 차이2375000  17500.0
Finance     Los Angeles   80000   최대와 최소의 차이720000   1500.0
            New York      70000   최대와 최소의 차이630000   1000.0
Marketing   Beijing       60000   최대와 최소의 차이540000  30000.0
            Hong Kong     45000   최대와 최소의 차이405000  23000.0

salary 100000이상인것, 그렇지 않은것으로 2개의 그룹으로 구분하고
각 그룹에서 Division + City 문자열을 결합하는데
첫번재 그룹에는 결합된 문자열의 5번을 결합하여 red column에 추가하고
그렇지 않은 그룹에는 2번 결합하여 red column에 추가