In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
import pandas as pd

In [3]:
# 1. 예제 데이터프레임 생성 (이걸 파일로 저장한다고 가정)
df_final = pd.DataFrame({
    '이름': ['철수', '영희', '민수'],
    '최종점수': [95, 88, 92]
})

# 2. 엑셀 파일로 저장하기
df_final.to_excel('성적표.xlsx', index=False)
print("파일 저장 완료!")

# 3. 저장된 파일 다시 불러오기
df_read = pd.read_excel('성적표.xlsx')
print(df_read.head())

파일 저장 완료!
   이름  최종점수
0  철수    95
1  영희    88
2  민수    92

In [29]:
df = pd.read_csv('경기도 성남시_성남 미디어센터 공간정보_20250529.csv', encoding='cp949')
df

,공간명,대여가능 여부,대여대상,대여기준대상,리스트페이지(URL),이용안내,지원시설,비고,데이터기준일자
0,다목적스튜디오(영상),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,"간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...",기본으로 영상의 경우 블루 스크린과 HD급 카메라 3대가 제공됩니다. 실시간 스트...,실시간 스트리밍이 가능하도록 기본세팅과 간단한 사용교육을 도와드립니다. * 카메라...,2025-05-29
1,다목적스튜디오(포토),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,"간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...",사진용 조명 2개를 제공합니다. 블루스크린을 사용 할 수 있습니다. 배경지는 제...,* 사진용 카메라는 미디어센터에서 대여하거나 본인이 지참하시기 바랍니다. * 카메라...,2025-05-29
2,소리스튜디오,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"라디오 진행과 영상에 필요한 내레이션 녹음이가능한 소리스튜디오입니다. 유튜브, 아프...","영상촬영용 카메라 2대(스튜디오 전체 촬영 1대, 카메라줌 및각도 조절이 가능한 카...","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
3,일반강의실,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"소규모를 대상으로 모임이나 회의, 세미나가 가능한 일반강의실입니다. 일반강의실은 2...","모니터 겸 전자칠판(99인치), 테이블, 의자, 칠판 운영가능","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
4,미디어공방(실시간 1인방송 및 영상편집실),대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,실시간 1인방송에 최적회되 공간입니다. FULL HD 동영상 까지 편집이 가능합니다...,실시간 방송용 컴퓨터 1대(OBS 프로그램 설치) 편집용 컴퓨터 1대(어도비 C...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭 ...",2025-05-29
5,미디어공방(전문편집실) 2,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,FULL HD 동영상 까지 편집이 가능한 미디어공방입니다. 미디어공방은 작업할 수 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
6,미디어홀(상영관),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,작은 상영회부터 발표회까지 다방면으로 사용가능한 미디어홀입니다. 미디어홀은 관객석 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
7,디지털교육실1,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"소규모를 대상으로미디어교육 진행가능,실습이 가능한 디지털교육실1입니다. 디지털교육실...","고사양 PC,27"" 모니터 각14대 설치 프로그램 Adobe CCMaster Col...","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
8,디지털교육실2,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"소규모를 대상으로미디어교육 진행가능,실습이 가능한 디지털교육실2입니다. 디지털교육실...",2인용 책상 6개 의자12개 전자칠판(인터랙티브화이트보드) 1개 - 98인치/ 4K...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
9,영상변환(VHS 테이프 디지털 영상 변환),대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"** <필독> VHS, 6mm 테이프,8mm 테이프(VHS-C) 변환 지원 가능합니...",* VHS 테이프: VHS플레이어 2대 + 노크북2대 * 6MM 테이프: 6MM ...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
10,동아리방1,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,동아리방 1번은 기획회의 및 미디어관련 모임을 위해 마련된 공간입니다. 최대 6인 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭 ...",2025-05-29
11,동아리방2,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,동아리방 2번은 기획회의 및 미디어관련 모임을 위해 마련된 공간입니다. 최대 6인 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭 ...",2025-05-29

In [17]:
#데이터 상위 3개 행만 출력
df.head(3)
#어떤 컬럼들이 있는지, 그리고 비어있는 값(결측치)이 있는지 한눈에 확인하는 명령어
df.info()
#'대여가능 여부' 컬럼에는 어떤 종류의 값들이 있는지 확인해보기
df['대여가능 여부'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   공간명          12 non-null     object
 1   대여가능 여부      12 non-null     object
 2   대여대상         12 non-null     object
 3   대여기준대상       12 non-null     int64
 4   리스트페이지(URL)  12 non-null     object
 5   이용안내         12 non-null     object
 6   지원시설         8 non-null      object
 7   비고           12 non-null     object
 8   데이터기준일자      12 non-null     object
dtypes: int64(1), object(8)
memory usage: 996.0+ bytes

array(['대여가능'], dtype=object)

In [22]:
#'대여가능 여부'가 '대여가능'인 장소들만 골라서 새로운 변수 available_df에 저장
available_df = df[df['대여가능 여부']=='대여가능']
available_df['공간명']

0                 다목적스튜디오(영상)
1                 다목적스튜디오(포토)
2                      소리스튜디오
3                       일반강의실
4     미디어공방(실시간 1인방송 및 영상편집실)
5              미디어공방(전문편집실) 2
6                   미디어홀(상영관)
7                     디지털교육실1
8                     디지털교육실2
9     영상변환(VHS 테이프 디지털 영상 변환)
10                      동아리방1
11                      동아리방2
Name: 공간명, dtype: object

In [24]:
#'공간명'에 '스튜디오'라는 단어가 포함된 장소들만 찾아보기
df[df['공간명'].str.contains('스튜디오')]

,공간명,대여가능 여부,대여대상,대여기준대상,리스트페이지(URL),이용안내,지원시설,비고,데이터기준일자
0,다목적스튜디오(영상),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,"간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...",기본으로 영상의 경우 블루 스크린과 HD급 카메라 3대가 제공됩니다. 실시간 스트...,실시간 스트리밍이 가능하도록 기본세팅과 간단한 사용교육을 도와드립니다. * 카메라...,2025-05-29
1,다목적스튜디오(포토),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,"간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...",사진용 조명 2개를 제공합니다. 블루스크린을 사용 할 수 있습니다. 배경지는 제...,* 사진용 카메라는 미디어센터에서 대여하거나 본인이 지참하시기 바랍니다. * 카메라...,2025-05-29
2,소리스튜디오,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"라디오 진행과 영상에 필요한 내레이션 녹음이가능한 소리스튜디오입니다. 유튜브, 아프...","영상촬영용 카메라 2대(스튜디오 전체 촬영 1대, 카메라줌 및각도 조절이 가능한 카...","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29

In [34]:
#'대여기준대상'이 3 이상인 장소의 '공간명'과 '이용안내' 컬럼만 출력
rental_target = df[df['대여기준대상']>=3]
rental_target[['공간명','이용안내']]

           공간명                                               이용안내
0  다목적스튜디오(영상)  간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...
1  다목적스튜디오(포토)  간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...
6    미디어홀(상영관)  작은 상영회부터 발표회까지 다방면으로 사용가능한 미디어홀입니다. 미디어홀은 관객석 ...

In [35]:
#'대여대상'별로 공간이 각각 몇 개씩 있는지 세어보기
df.groupby('대여대상')['공간명'].value_counts()

대여대상        공간명
전체(비회원 제외)  다목적스튜디오(영상)                1
            다목적스튜디오(포토)                1
            동아리방1                      1
            동아리방2                      1
            디지털교육실1                    1
            디지털교육실2                    1
            미디어공방(실시간 1인방송 및 영상편집실)    1
            미디어공방(전문편집실) 2             1
            미디어홀(상영관)                  1
            소리스튜디오                     1
            영상변환(VHS 테이프 디지털 영상 변환)    1
            일반강의실                      1
Name: count, dtype: int64

In [51]:
#지원시설 컬럼에 '카메라'라는 단어가 포함된 데이터만 필터링
df[df['지원시설'].str.contains('카메라').notna()]

,공간명,대여가능 여부,대여대상,대여기준대상,리스트페이지(URL),이용안내,지원시설,비고,데이터기준일자
0,다목적스튜디오(영상),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,"간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...",기본으로 영상의 경우 블루 스크린과 HD급 카메라 3대가 제공됩니다. 실시간 스트...,실시간 스트리밍이 가능하도록 기본세팅과 간단한 사용교육을 도와드립니다. * 카메라...,2025-05-29
1,다목적스튜디오(포토),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,"간단한 사진부터 뉴스제작, 실시간 인터넷방송 등 촬영할 수 있는 다목적스튜디오입니다...",사진용 조명 2개를 제공합니다. 블루스크린을 사용 할 수 있습니다. 배경지는 제...,* 사진용 카메라는 미디어센터에서 대여하거나 본인이 지참하시기 바랍니다. * 카메라...,2025-05-29
2,소리스튜디오,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"라디오 진행과 영상에 필요한 내레이션 녹음이가능한 소리스튜디오입니다. 유튜브, 아프...","영상촬영용 카메라 2대(스튜디오 전체 촬영 1대, 카메라줌 및각도 조절이 가능한 카...","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
3,일반강의실,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"소규모를 대상으로 모임이나 회의, 세미나가 가능한 일반강의실입니다. 일반강의실은 2...","모니터 겸 전자칠판(99인치), 테이블, 의자, 칠판 운영가능","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
4,미디어공방(실시간 1인방송 및 영상편집실),대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,실시간 1인방송에 최적회되 공간입니다. FULL HD 동영상 까지 편집이 가능합니다...,실시간 방송용 컴퓨터 1대(OBS 프로그램 설치) 편집용 컴퓨터 1대(어도비 C...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭 ...",2025-05-29
7,디지털교육실1,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"소규모를 대상으로미디어교육 진행가능,실습이 가능한 디지털교육실1입니다. 디지털교육실...","고사양 PC,27"" 모니터 각14대 설치 프로그램 Adobe CCMaster Col...","예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
8,디지털교육실2,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"소규모를 대상으로미디어교육 진행가능,실습이 가능한 디지털교육실2입니다. 디지털교육실...",2인용 책상 6개 의자12개 전자칠판(인터랙티브화이트보드) 1개 - 98인치/ 4K...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29
9,영상변환(VHS 테이프 디지털 영상 변환),대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"** <필독> VHS, 6mm 테이프,8mm 테이프(VHS-C) 변환 지원 가능합니...",* VHS 테이프: VHS플레이어 2대 + 노크북2대 * 6MM 테이프: 6MM ...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29

In [61]:
#이용안내 컬럼의 글자 수를 계산해 새로운 컬럼 설명길이를 만들고, 가장 긴 순서대로 정렬
df['설명길이'] = df['이용안내'].str.len()
df['설명길이'].sort_values(ascending=False)

9     858
10    456
11    456
5     412
6     409
2     341
3     315
4     312
0     294
1     294
7     287
8     277
Name: 설명길이, dtype: int64

In [62]:
df[['공간명','데이터기준일자']].to_excel('공간명_데이터기준일자.xlsx', index=False)

In [64]:
# 이용안내 컬럼에서 '주차권'이라는 단어가 포함된 행만 찾아보기
df[df['이용안내'].str.contains('주차권')]

,공간명,대여가능 여부,대여대상,대여기준대상,리스트페이지(URL),이용안내,지원시설,비고,데이터기준일자,설명길이
6,미디어홀(상영관),대여가능,전체(비회원 제외),3,http://www.snmedia.or.kr/rental/space.asp,작은 상영회부터 발표회까지 다방면으로 사용가능한 미디어홀입니다. 미디어홀은 관객석 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29,409
9,영상변환(VHS 테이프 디지털 영상 변환),대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,"** <필독> VHS, 6mm 테이프,8mm 테이프(VHS-C) 변환 지원 가능합니...",* VHS 테이프: VHS플레이어 2대 + 노크북2대 * 6MM 테이프: 6MM ...,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭▶...",2025-05-29,858
10,동아리방1,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,동아리방 1번은 기획회의 및 미디어관련 모임을 위해 마련된 공간입니다. 최대 6인 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭 ...",2025-05-29,456
11,동아리방2,대여가능,전체(비회원 제외),1,http://www.snmedia.or.kr/rental/space.asp,동아리방 2번은 기획회의 및 미디어관련 모임을 위해 마련된 공간입니다. 최대 6인 ...,NaN,"예약 취소시에는 로그인 ▶홈페이지 우측 상단 ""마이페이지"" 클릭 ▶ 이용현황 클릭 ...",2025-05-29,456

In [68]:
# 리스트페이지(URL) 컬럼에서 중복을 제거한 고유 값이 몇 개인지 확인
df['리스트페이지(URL)'].nunique()

1

In [83]:
# 지원시설에 '카메라'가 포함되어 있고, 동시에 비고에 '교육'이라는 단어가 포함된 공간의 이름을 출력
space = df[df['지원시설'].str.contains('카메라') & df['비고'].str.contains('교육')]
space['공간명']
df['대여가능 여부'].replace('대여가능', 'Available')

0     Available
1     Available
2     Available
3     Available
4     Available
5     Available
6     Available
7     Available
8     Available
9     Available
10    Available
11    Available
Name: 대여가능 여부, dtype: object